- name: Remove older versions of Docker package
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install ca-certificates, curl, gnupg and lsb-release
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Create a directory /etc/apt/keyrings if it does not exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: Get dpkg architecture
  ansible.builtin.shell: dpkg --print-architecture
  register: DPKG_ARCHITECTURE

- name: Get lsb_release
  ansible.builtin.shell: lsb_release -cs
  register: LSB_RELEASE

- name: Create apt source list
  ansible.builtin.blockinfile:
    path: /etc/apt/sources.list.d/docker.list
    block: |
      deb [arch={{ DPKG_ARCHITECTURE.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ LSB_RELEASE.stdout }} stable

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Update the apt package index, and install the latest version of Docker Engine, containerd, and Docker Compose
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Testing docker run command
  ansible.builtin.shell: docker run hello-world
  register: DOCKER_RUN_RC
  failed_when: DOCKER_RUN_RC.rc != 0

- name: Create daemon.json
  ansible.builtin.blockinfile:
    path: /etc/docker/daemon.json
    block: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }

- name: Create a directory /etc/systemd/system/docker.service.d if it does not exist
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Restart and enable service docker and reload the daemon
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
    enabled: true

- name: Add the user ubuntu, appending the group docker to the user's groups
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: true
