- name: Create containerd.conf
  ansible.builtin.blockinfile:
    path: /etc/modules-load.d/containerd.conf
    block: |
      overlay
      # https://docs.oracle.com/cd/F33069_01/start/netfilter.html
      br_netfilter

- name: Add the overlay and br_netfilter module
  ansible.builtin.modprobe:
    name:
      - overlay
      - br_netfilter
    state: present

- name: Edit the kernal parameter
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    block: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Execute sysctl --system
  ansible.builtin.shell: sysctl --system

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add an Apt signing key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get lsb_release
  ansible.builtin.shell: lsb_release -cs
  register: LSB_RELEASE

- name: Get dpkg architecture
  ansible.builtin.shell: dpkg --print-architecture
  register: DPKG_ARCHITECTURE

- name: Add the Docker repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ DPKG_ARCHITECTURE.stdout }}] https://download.docker.com/linux/ubuntu {{ LSB_RELEASE.stdout }} stable"
    state: present

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install containerd.io
  ansible.builtin.apt:
    name: containerd.io

- name: Create a directory /etc/containerd if it does not exist
  ansible.builtin.file:
    path: /etc/containerd
    state: directory

- name: Get containerd config
  ansible.builtin.shell: containerd config default | sudo tee /etc/containerd/config.toml

- name: Restart and enable service containerd and reload the daemon
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true
    enabled: true
